// React-App/todo-app/src/components/ToDoForm.js
import { React } from "react";

const ToDoForm = ({ name, setName }) => {
  const nameTextHandler = (e) => {
    let nameError = false;
    if (e.target.value === undefined || e.target.value === "") {
      nameError = true;
    } else {
      nameError = false;
    }
    setName({
      value: e.target.value,
      error: nameError ? "Name is required." : "",
    });
  };

  const isDisabled = () => {
    return name.value !== null && name.value !== "";
  };
  return (
    <div className="row mt-5">
      <form className="form text-center container mx-auto">
        <div className="row">
          <div className="col-md-4 mt-3">
            <label className="form-label" htmlFor="taskName">
              Task Name
            </label>
            <input
              type="text"
              className="form-control"
              id="taksName"
              placeholder="Task Name"
              onChange={nameTextHandler}
              value={name.value}
            />
            <p className="text-danger">{name.error}</p>
          </div>
          <div className="col-md-4 mt-3">
            <label className="form-label" htmlFor="taskPriority">
              Priority
            </label>
            <select
              className="form-select"
              name="taskPriority"
              placeholder="Priority"
              aria-label="Priority"
            >
              <option value="">Priority</option>
              <option value="1">High</option>
              <option value="2">Medium</option>
              <option value="3">Low</option>
            </select>
            <p className="text-danger">Priority is required.</p>
          </div>
          <div className="col-md-4 mt-3">
            <label className="form-label" htmlFor="taskStatus">
              Status
            </label>
            <select
              className="form-select"
              name="taskStatus"
              placeholder="Status"
              aria-label="Status"
            >
              <option value="">Status</option>
              <option value="1">To Do</option>
              <option value="2">In Progress</option>
              <option value="3">Done</option>
            </select>
            <p className="text-danger">Status is required.</p>
          </div>
        </div>
        <div className="row mt-3">
          <button
            disabled={!isDisabled()}
            type="submit"
            className="form-control btn btn-success"
          >
            Save
          </button>
        </div>
      </form>
    </div>
  );
};

export default ToDoForm;

// Angular-App/todo-app/src/app/components/todo-form/todo-form.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';

@Component({
  selector: 'todo-form',
  templateUrl: './todo-form.component.html',
  styleUrls: ['./todo-form.component.css'],
})
export class TodoFormComponent implements OnInit {
  taskForm = this.fb.group({
    taskName: ['', Validators.required],
    taskPriority: ['', Validators.required],
    taskStatus: ['', Validators.required],
  });

  get taskName() {
    return this.taskForm.get('taskName');
  }

  get taskPriority() {
    return this.taskForm.get('taskPriority');
  }

  get taskStatus() {
    return this.taskForm.get('taskStatus');
  }

  constructor(private fb: FormBuilder) {}

  ngOnInit(): void {}

  onSubmit() {
    if (this.taskForm.valid) {
      console.log(this.taskName?.value);
      console.log(this.taskPriority?.value);
      console.log(this.taskStatus?.value);
      this.resetForm();
    } else {
      console.log('Invalid');
    }
  }

  resetForm() {
    this.taskForm.reset();
    this.taskForm.patchValue({
      taskName: '',
      taskPriority: '',
      taskStatus: '',
    });
  }
}

<div class="container mx-auto mt-5">
  <div class="row">
    <div class="col-md-12">
      <form
        [formGroup]="taskForm"
        (ngSubmit)="onSubmit()"
        class="form text-center container mx-auto"
      >
        <div class="row">
          <div class="col-md-4 mt-3">
            <label class="form-label" for="taskName">Task Name</label>
            <input
              type="text"
              class="form-control"
              id="taksName"
              placeholder="Task Name"
              formControlName="taskName"
            />
            <p
              class="text-danger"
              *ngIf="
                taskName?.invalid &&
                (taskName?.dirty || taskName?.touched) &&
                taskName?.errors?.required
              "
            >
              Name is required.
            </p>
          </div>
          <div class="col-md-4 mt-3">
            <label class="form-label" for="taskPriority">Priority</label>
            <select
              class="form-select"
              name="taskPriority"
              placeholder="Priority"
              aria-label="Priority"
              formControlName="taskPriority"
            >
              <option value="">Priority</option>
              <option value="1">High</option>
              <option value="2">Medium</option>
              <option value="3">Low</option>
            </select>
            <p
              class="text-danger"
              *ngIf="
                taskPriority?.invalid &&
                (taskPriority?.dirty || taskPriority?.touched) &&
                taskPriority?.errors?.required
              "
            >
              Priority is required.
            </p>
          </div>
          <div class="col-md-4 mt-3">
            <label class="form-label" for="taskStatus">Status</label>
            <select
              class="form-select"
              name="taskStatus"
              placeholder="Status"
              aria-label="Status"
              formControlName="taskStatus"
            >
              <option value="">Status</option>
              <option value="1">To Do</option>
              <option value="2">In Progress</option>
              <option value="3">Done</option>
            </select>
            <p
              class="text-danger"
              *ngIf="
                taskStatus?.invalid &&
                (taskStatus?.dirty || taskStatus?.touched) &&
                taskStatus?.errors?.required
              "
            >
              Status is required.
            </p>
          </div>
        </div>
        <div class="row mt-3">
          <button
            [disabled]="!taskForm.valid"
            type="submit"
            class="form-control btn btn-primary"
          >
            Save
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
